#include "register.h"
#include "instruction.h"

Asm_Register register_table[] = {
	{"rax", 0x0, REG | QWORD},
	{"rcx", 0x1, REG | QWORD},
	{"rdx", 0x2, REG | QWORD},
	{"rbx", 0x3, REG | QWORD},
	{"rsp", 0x4, REG | QWORD},
	{"rbp", 0x5, REG | QWORD},
	{"rsi", 0x6, REG | QWORD},
	{"rdi", 0x7, REG | QWORD},
	{"r8", 0x8, REG | QWORD},
	{"r9", 0x9, REG | QWORD},
	{"r10", 0xA, REG | QWORD},
	{"r11", 0xB, REG | QWORD},
	{"r12", 0xC, REG | QWORD},
	{"r13", 0xD, REG | QWORD},
	{"r14", 0xE, REG | QWORD},
	{"r15", 0xF, REG | QWORD},

	{"eax", 0x0, REG | DWORD},
	{"ecx", 0x1, REG | DWORD},
	{"edx", 0x2, REG | DWORD},
	{"ebx", 0x3, REG | DWORD},
	{"esp", 0x4, REG | DWORD},
	{"ebp", 0x5, REG | DWORD},
	{"esi", 0x6, REG | DWORD},
	{"edi", 0x7, REG | DWORD},
	{"r8d", 0x8, REG | DWORD},
	{"r9d", 0x9, REG | DWORD},
	{"r10d", 0xA, REG | DWORD},
	{"r11d", 0xB, REG | DWORD},
	{"r12d", 0xC, REG | DWORD},
	{"r13d", 0xD, REG | DWORD},
	{"r14d", 0xE, REG | DWORD},
	{"r15d", 0xF, REG | DWORD},

	{"ax", 0x0, REG | WORD},
	{"cx", 0x1, REG | WORD},
	{"dx", 0x2, REG | WORD},
	{"bx", 0x3, REG | WORD},
	{"sp", 0x4, REG | WORD},
	{"bp", 0x5, REG | WORD},
	{"si", 0x6, REG | WORD},
	{"di", 0x7, REG | WORD},
	{"r8w", 0x8, REG | WORD},
	{"r9w", 0x9, REG | WORD},
	{"r10w", 0xA, REG | WORD},
	{"r11w", 0xB, REG | WORD},
	{"r12w", 0xC, REG | WORD},
	{"r13w", 0xD, REG | WORD},
	{"r14w", 0xE, REG | WORD},
	{"r15w", 0xF, REG | WORD},

	{"al", 0x0, REG | BYTE},
	{"cl", 0x1, REG | BYTE},
	{"dl", 0x2, REG | BYTE},
	{"bl", 0x3, REG | BYTE},
	{"spl", 0x4, REG | BYTE},
	{"bpl", 0x5, REG | BYTE},
	{"sil", 0x6, REG | BYTE},
	{"dil", 0x7, REG | BYTE},
	{"r8b", 0x8, REG | BYTE},
	{"r9b", 0x9, REG | BYTE},
	{"r10b", 0xA, REG | BYTE},
	{"r11b", 0xB, REG | BYTE},
	{"r12b", 0xC, REG | BYTE},
	{"r13b", 0xD, REG | BYTE},
	{"r14b", 0xE, REG | BYTE},
	{"r15b", 0xF, REG | BYTE},

	{"ah", 0x0, REG | BYTE},
	{"ch", 0x1, REG | BYTE},
	{"dh", 0x2, REG | BYTE},
	{"bh", 0x3, REG | BYTE},
	{"spl", 0x4, REG | BYTE},
	{"bpl", 0x5, REG | BYTE},
	{"sil", 0x6, REG | BYTE},
	{"dil", 0x7, REG | BYTE},
	{"r8b", 0x8, REG | BYTE},
	{"r9b", 0x9, REG | BYTE},
	{"r10b", 0xA, REG | BYTE},
	{"r11b", 0xB, REG | BYTE},
	{"r12b", 0xC, REG | BYTE},
	{"r13b", 0xD, REG | BYTE},
	{"r14b", 0xE, REG | BYTE},
	{"r15b", 0xF, REG | BYTE},
};

size_t num_registers = sizeof(register_table) / sizeof(register_table[0]);
